public class AllCCsLoader {

    @Auraenabled
    public static void iloader(){
     
        CCLoaderFinal kn=new CCLoaderFinal();
		kn.executeme();
        
    }
    
     @Auraenabled
    public static void iloader3(){
     
       CCLoaderFinal2 kn2=new CCLoaderFinal2();
       kn2.executeme();
       
    }
     @Auraenabled
    public static void iloader4(){
     
       
        CCLoaderFinal3 kn3=new CCLoaderFinal3();
        kn3.executeme();
       
       
    }
    @Auraenabled
    public static void iloader5(){
     
        CCLoaderFinal4 kn4=new CCLoaderFinal4();
        kn4.executeme();
       
    }
    
    
    @Auraenabled
    public static void iloader2(){
     
       
        //updating margin and margin percentage
        UpdateCCList nr=new UpdateCCList();
		nr.executeme();
    }
}